config/routes.rb
Rails.application.routes.draw do

	root to: "projects#index", as: 'home'

  resources :todos
  resources :projects

  resources :projects do
		resources :todos
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :todos
end

app/models/todo.rb
class Todo < ApplicationRecord
	has_one :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
    	@projects = Project.all
  	end

  	def show
  	end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todo = Todo.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @todo = Todo.new
  end

  # GET /projects/1/edit
  def edit
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to projects_url
  end

  def update
    respond_to do |format|
      if @todo.update(project_params)
        format.html { redirect_to @todo, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  	def set_project
      @todo = Todo.find(params[:id])
    end
    def todo_params
      params.require(:todo).permit(:text, :isCompleted, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyapp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application.css', media: 'all' %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js" %>
    <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" %>
    <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js" %>
    <%= javascript_include_tag 'application.js' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<meta charset="utf-8">
<meta content="width=device-width" name="viewport">


<div class="navbar navbar-dark bg-todo shadow-sm">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <div id="AlertDiv">
        <h3>Задачи</h3>
      </div>
    </a>
    <a id="add_todo" href="#">
      <img src="assets/plus.png" id="plus">
    </a>
  </div>
</div>


<div class="container"">
  <div class="row padded">
    <% @projects.each do |project| %>
    <div class="card block_card col-lg-3 col-md-5" >
      <div class="card-body">
        <h5 class="card-title">
          <span style="font-size: 20px; text-transform: uppercase;"><%= project.title %></span>
        </h5>
        <hr>
        <p class="card-text">
          <div class="demo-list clear"> 
            <% project.todos.each do |todo| %>
            <%= form_for :todo, url: todos_path, :html => { :id => "form" + todo.id.to_s } do |f| %>
            <input tabindex="<%= todo.id %>" type="checkbox" id="checkbox_<%= todo.id %>" name="todo[isCompleted]">
            <% if todo.isCompleted %>
            <label for="checkbox_<%= todo.id %>" id="label_<%= todo.id %>" style="text-decoration: line-through">
              <% else %>
              <label for="checkbox_<%= todo.id %>" id="label_<%= todo.id %>" style="text-decoration: none">
                <% end %>
                <%= todo.text %>
              </label>
              <br>
              <% end %>
              <% end %>
            </div>
          </p>

        </div>
      </div>
      <% end %>
    </div>
  </div>



  <div id="container">
    <div id="exampleModal" class="reveal-modal">
    </div>
  </div>


  <div id="add_todo_blank" style="visibility: hidden;">
    <div id="Card" class="card-body">
      <p class="card-title" style="font-size: 20px; text-transform: uppercase; text-align: center;">
        Новая задача
      </p>
      <hr>
      <%= form_for :todo, url: todos_path, :html => { :id => "my_form" } do |f| %>
      <p>
        <%= f.text_field(:text, id: 'txt', class: 'form-control') %>
      </p>
      <p>
        <%= f.select :project_id, Project.all.collect { |p| [ p.title, p.id ] }, include_blank: false %>
      </p>
      <p>
        <a class="btn btn-primary" href="javascript:{}" id="reset" >
          ОТМЕНА
        </a>
        <a class="btn btn-primary" href="javascript:{}" onclick="document.getElementById('my_form').submit(); return false;">
          OK
        </a>
      </p>
      <p>
      </p>
      <% end %>
    </div>
  </div>





  <script>
    $(document).ready(function(){
      var callbacks_list = $('.demo-callbacks ul');
      $('.demo-list input').on('ifCreated ifClicked ifChanged ifChecked ifUnchecked ifDisabled ifEnabled ifDestroyed', function(event){
        callbacks_list.prepend('<li><span>#' + this.id + '</span> is ' + event.type.replace('if', '').toLowerCase() + '</li>');
      }).iCheck({
        checkboxClass: 'icheckbox_square-blue',
        radioClass: 'iradio_square-blue',
        increaseArea: '20%'
      });
    });
  </script>


  <script type="text/javascript">


    <% @projects.each do |project| %>
    <% project.todos.each do |todo| %>
    <% if todo.isCompleted %>
    $('#checkbox_<%= todo.id %>').iCheck('check');
    <% end %>
    $('#checkbox_<%= todo.id %>').on('ifChecked', function () {
      document.getElementById('form<%= todo.id %>').submit();
      $('#label_<%= todo.id %>').attr("style", "text-decoration: line-through");
    });
    $('#checkbox_<%= todo.id %>').on('ifUnchecked', function () {
      document.getElementById('form<%= todo.id %>').submit();
      $('#label_<%= todo.id %>').attr("style", "text-decoration: none");
    });
    <% end %>
    <% end %>

    $("select").attr("class","form-control");
    $("#add_todo").on("click", function () {
      $("#add_todo_blank").attr("style", "visibility: visible");
      $("#container").attr("style","visibility: visible; display: block;");
    });

    $("#reset").on("click", function () {
      $('#todo_project_id option').prop('selected', function() {
        return this.defaultSelected;
      });
      document.getElementById("txt").value = "";
      $("#add_todo_blank").attr("style", "visibility: hidden");
      $("#container").attr("style","visibility: hidden; display: none;");

      $(document).ready(function(){
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
    increaseArea: '20%' // не обязательно
  });
      });

    });



  </script>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>